apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app  # This label should match your ServiceMonitor
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: my-app  # This selector should match the labels of the Pods
  template:
    metadata:
      labels:
        app: my-app  # Ensure this label matches
      annotations:
        prometheus.io/scrape: "true"         # Enable scraping
        prometheus.io/port: "3000"           # Default metrics port
        prometheus.io/path: "/metrics"       # Path for metrics of the first app
        promtail.io/scrape: "true"
        promtail.io/path: "/usr/src/app/app1/*.log"
    spec:
      containers:
        - name: my-app
          image: faisalkamil/check
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"  # Minimum CPU required for autoscaling
              memory: "256Mi"  # Minimum Memory required for autoscaling
            limits:
              cpu: "400m"  # Maximum CPU
              memory: "512Mi"  # Maximum Memory
          ports:
            - containerPort: 3000  # First app

---

apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  type: NodePort  # Set the service type to NodePort
  ports:
    - name: app1
      port: 80              # Port exposed by the service for the first app
      targetPort: 3000      # Target port on the pod for the first app
      nodePort: 30001       # Optional: Specify a NodePort (or leave it out for automatic assignment)
  selector:
    app: my-app  # This should match the Pod labels
